# Generated by Django 5.0.2 on 2024-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='registration',
            name='pnum',
            field=models.CharField(max_length=25),
        ),
    ]
