# Generated by Django 5.0.2 on 2024-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_remove_registration_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pnum',
            field=models.CharField(max_length=255),
        ),
    ]
